service: 'techland'

provider: 
    name: aws
    runtime: nodejs16.x
    profile: land
    stage: dev
    region : ap-south-1
    


functions: 
  app:
    handler: index.handler
    timeout: 300
    events:
      - http: 
          path: "*"
          method: "*"
          cors: true
      - http: 
          path: /{proxt+}
          method: "*"
          cors: true

plugins: 
  - serverless-offline 